name: Kubescape scanning for misconfigurations

on: [push, pull_request]

jobs:
  test_ks_misconfigurations:
    uses: kubescape/workflows/.github/workflows/ks-ga-flow.yaml@main
    secrets: inherit
    #test pr