name: Kubescape scanning for misconfigurations

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]    
jobs:
  test_ks_misconfigurations:
    uses: kubescape/workflows/.github/workflows/ks-ga-flow.yaml@main
    secrets: inherit
    #test pr