name: PR Comment Trigger

on:
  issue_comment:
    types: [created]
jobs:
  job01:
    if: ${{ github.event.issue.pull_request }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: say hello
        if: contains(toLower(github.event.comment.body), '/support')  # check the comment if it contains the keywords
        run: |
          echo "Line 14 PR MSG"
          
      - name: test
        if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
        run: |
          echo "Line 18 PR MSG"
