name: Push to Armosec Repo

on:
  pull_request:
    branches:
      - master
env:
  PRIVATE_REPO_URL: ${{ secrets.PRIVATE_ARMOSEC_URL }}
  PRIVATE_REPO_USERNAME: ${{ secrets.PRIVATE_REPO_USERNAME }}
  PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run export script
        run: |
          OUTPUT=pre-release python ./scripts/export.py
          rm -r releaseDev
          cp -R pre-release releaseDev

      - name: Configure Git Credentials
        run: |
          git config --global user.name "${PRIVATE_REPO_USERNAME}"
          git config --global user.email "${PRIVATE_REPO_EMAIL}"

      - name: Push Changes
        run: |
          git remote add private-repo "${PRIVATE_ARMOSEC_URL}"
          git checkout -b temp-branch
          git add .
          git commit -m "Pushing changes from source repo"
          git push private-repo temp-branch:main